[package]
name = "auth"
version = "0.1.0"
edition = "2024"
description = "ideabase auth module"

[dependencies]
common = { path = "../common/core" }

log = {  version = "0.4" }
tokio = { version = "1.44", features = ["full"]}


[dev-dependencies]
tokio-test = "0.4"
