cache:
  dir: /Users/zk/Downloads/cache

# 数据源 192.168.31.41
datasource:
  host: 192.168.31.41
  port: 3306
  username: root
  password: keke*de*2025

# 向量数据库
vector:
  schema: http
  host: 127.0.0.1
  port: 6333