services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    command: [
      "postgres",
      "-c", "timezone=Asia/Shanghai",
      "-c", "wal_level=logical",
      "-c", "max_wal_senders=10",
      "-c", "max_replication_slots=10"
    ]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ideabase2025
      POSTGRES_DB: ideabase
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      REDIS_ARGS: "--requirepass Ideabase2025"
    ports:
      - 6379:6379
      - 8001:8001
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
  mysql:
    container_name: mysql
    image: mysql:9.3.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=ideabase2025
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    command:
      - --log_bin=mysql-bin
      - --server-id=1
      - --character-set-server=utf8mb4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .sql-demo/init.sql:/docker-entrypoint-initdb.d/init.sql
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.14.0
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - TZ=Asia/Shanghai
      - QDRANT__SERVICE__API_KEY=ideabase2025
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

#  ideabase:
#    container_name: ideabase
#    image: cc/ideabase:latest
#    ports:
#      - 8080:8080
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#    env_file:
#      - Docker-run-env.properties
#    depends_on:
#      - qdrant
#      - mysql
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - .docker/volume/cache:/opt/cache/ideabase
#      - .json-demo/vector.json:/app/yaml/vector.json